---
- hosts: web
  become: yes
  vars_files:
    - vars/default.yml
  gather_facts: true
  tasks:
    - name: Instalação de pacotes webserver
      apt:
        pkg:
          - php7.4
          - php-pear
          - php7.4-curl
          - php7.4-gd
          - php7.4-intl
          - php7.4-xmlrpc
          - php7.4-mysql
          - apache2
          - python3-mysqldb
          - wget
          - zip
          - curl
          - vim
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"
    - name: 'Diretorio webserver'
      become: yes
      file:
        path: /srv/www
        state: directory
        owner: "{{ app_user }}"
        mode: '0755' 
